### ISSUE TITLE
AE2 Wireless Crafting Terminal Out of range ~1 meter away

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#203] opened 2023-02-28 00:25 UTC
**Pack Version:** 13.0.0 HT
**Mod Name:** Applied Energistics 2

**Describe the bug**
My wireless terminal always says out of range.

**To Reproduce**
1. Link wireless crafting terminal to network
2. charge wireless terminal
3. Install wireless access point
4. Right click with wireless crafting terminal

**Expected behavior**
Wireless terminal opens up access to my stuff

**Screenshots**

![2023-02-27_18 21 06](https://user-images.githubusercontent.com/3300206/221720094-eb0959ed-1f70-4479-b619-a573f1f58a89.png)

**Additional context**
Could it be because of chunk claiming? No, I tried that.

**Comment by chimericdream** [comment] 2023-03-28 04:21
Closing as unable to reproduce and since it may have been a setup issue with the AE network.

**Closed as completed by chimericdream** 2023-03-28 04:21 UTC
Labels: bug
